#theme: jekyll-theme-tactile
#google_analytics: UA-3845189-1
remote-theme: pmarsceill/just-the-docs
#
title: Spatial Math Toolbox for MATLAB
description: "A free MATLAB Toolbox for representing position, orientation and pose in 2D and 3D"
ga_tracking: UA-3845189-1
aux_links:
  "Spatial Math Toolbox for MATLAB":
    - "https://github.com/petercorke/spatial-math"
footer_content: "Copyright &copy; Peter Corke. Distributed at <a href=\"http    s://github.com/petercorke/spatial-math\">Spatial Math Toolbox for MATLAB</a>    "

#theme: jekyll-theme-minimal
remote_theme: pmarsceill/just-the-docs
